-- Q4
CREATE TABLE EMPLOYEE_LIST(
    ID INT,
    NAME VARCHAR(30),
    MONTHLY_SALARY INT
);

INSERT INTO EMPLOYEE_LIST VALUES( 1, 'allen', 3000);
INSERT INTO EMPLOYEE_LIST VALUES( 2, 'adi', 6000);
INSERT INTO EMPLOYEE_LIST VALUES( 3, 'binu', 20000);
INSERT INTO EMPLOYEE_LIST VALUES( 4, 'ciju', 50000);
INSERT INTO EMPLOYEE_LIST VALUES( 5, 'dinu', 35000);

SELECT * FROM EMPLOYEE_LIST;

DECLARE
    CURSOR TEMP IS
    SELECT ID, NAME, MONTHLY_SALARY FROM EMPLOYEE_LIST;

    T TEMP%ROWTYPE;
    A INT;
    M INT;
BEGIN
    OPEN TEMP;
    LOOP
        FETCH TEMP INTO T;
        A:=T.MONTHLY_SALARY*12;
        IF(A<60000)THEN
            M:=T.MONTHLY_SALARY+(T.MONTHLY_SALARY*0.25);
        ELSIF(A<200000)THEN
            M:=T.MONTHLY_SALARY+(T.MONTHLY_SALARY*0.20);
        ELSIF(A<500000)THEN
            M:=T.MONTHLY_SALARY+(T.MONTHLY_SALARY*0.15);
        ELSE
            M:=T.MONTHLY_SALARY+(T.MONTHLY_SALARY*0.10);
        END IF;
        UPDATE EMPLOYEE_LIST SET MONTHLY_SALARY=M WHERE ID=T.ID;
        EXIT WHEN TEMP%NOTFOUND;
    END LOOP;

    CLOSE TEMP;
END;
/

SELECT * FROM EMPLOYEE_LIST;