-- CREATE A FUNCTION TO ADD TWO NUMBERS IN ORACLE

CREATE OR REPLACE FUNCTION ADD_TWO_NUMBERS (A NUMBER, B NUMBER) 
RETURN NUMBER IS
BEGIN
    RETURN A + B;
END;
/



-- CREATE A FUNCTION TO ADD TWO NUMBERS IN ORACLE WITH STORE RESULT IN VARIABLE

CREATE OR REPLACE FUNCTION ADD_TWO_NUMBERS (A NUMBER, B NUMBER) 
RETURN NUMBER IS
    RESULT NUMBER;
BEGIN
    RESULT := A + B;
    RETURN RESULT;
END;
/

-- SAMPLE CALL TO FUNCTION

SELECT ADD_TWO_NUMBERS(10, 20) FROM DUAL;

-- USING PLSQL BLOCK

DECLARE
    RESULT NUMBER;
BEGIN
    RESULT := ADD_TWO_NUMBERS(10, 20);
    DBMS_OUTPUT.PUT_LINE('RESULT: ' || RESULT);
END;
/

-- WRITE FUNCTION FOR FACTORIAL

CREATE OR REPLACE FUNCTION FACTORIAL (N NUMBER)
RETURN NUMBER IS
    RESULT NUMBER := 1;
BEGIN
    FOR I IN 1..N LOOP
        RESULT := RESULT * I;
    END LOOP;
    RETURN RESULT;
END;
/

-- CALL FACTORIAL FUNCTION IN PLSQL BLOCK

DECLARE
    RESULT NUMBER;
BEGIN
    RESULT := FACTORIAL(5);
    DBMS_OUTPUT.PUT_LINE('RESULT: ' || RESULT);
END;    
/

