-- Q3
CREATE TABLE PEOPLE_LIST(
    ID INT,
    NAME VARCHAR(30),
    DT_JOINING DATE,
    PLACE VARCHAR(30)
);

INSERT INTO PEOPLE_LIST VALUES( 100, 'allen', TO_DATE('10-04-2003', 'DD-MM-YYYY'), 'kerala' );
INSERT INTO PEOPLE_LIST VALUES( 102, 'adi', TO_DATE('11-11-2018', 'DD-MM-YYYY'), 'tamilnadu' );
INSERT INTO PEOPLE_LIST VALUES( 103, 'binu', TO_DATE('02-10-2017', 'DD-MM-YYYY'), 'japan' );
INSERT INTO PEOPLE_LIST VALUES( 104, 'ciju', TO_DATE('01-09-2001', 'DD-MM-YYYY'), 'america' );
INSERT INTO PEOPLE_LIST VALUES( 105, 'dinu', TO_DATE('06-07-2016', 'DD-MM-YYYY'), 'paris' );

SELECT * FROM PEOPLE_LIST;

CREATE TABLE EXP_LIST( ID INT, NAME VARCHAR(30), EX INT );

DECLARE
    CURSOR TEMP IS
    SELECT ID, NAME, DT_JOINING FROM PEOPLE_LIST;
    T  TEMP%ROWTYPE;
    EX INT;
BEGIN
    OPEN TEMP;
    LOOP
        FETCH TEMP INTO T;
        
        EX:=MONTHS_BETWEEN(SYSDATE, T.DT_JOINING)/12;
        IF EX>10 THEN
            INSERT INTO EXP_LIST VALUES( T.ID, T.NAME, EX );
        END IF;

        EXIT WHEN TEMP%NOTFOUND;
    END LOOP;
END;
/

SELECT * FROM EXP_LIST;
