-- Q1
CREATE TABLE BANKDETAILS(
    ACCNO INT,
    NAME VARCHAR2(15),
    BALANCE INT,
    ADATE DATE
);

INSERT INTO BANKDETAILS VALUES( 1001, 'aby', 3005, '10-oct-15' );
INSERT INTO BANKDETAILS VALUES( 1002, 'alan', 4000, '05-may-95' );
INSERT INTO BANKDETAILS VALUES( 1003, 'amal', 5000, '16-mar-92' );
INSERT INTO BANKDETAILS VALUES( 1004, 'jeffin', 3500, '01-apr-50' );

SELECT * FROM BANKDETAILS;

CREATE TABLE BANKNEW(
    ACCNO INT,
    INTR INT
);

-- CURSOR DEFINITION

DECLARE
    CURSOR TEMP IS
    SELECT
        ACCNO,
        NAME,
        BALANCE,
        ADATE
    FROM
        BANKDETAILS;

    TEMPVAR TEMP %ROWTYPE;
    INTR INT;
BEGIN
    OPEN TEMP;
    LOOP
        FETCH TEMP INTO TEMPVAR;
        INTR := .08 * TEMPVAR.BALANCE;
        INSERT INTO BANKNEW VALUES(
            TEMPVAR.ACCNO,
            INTR
        );
        EXIT WHEN TEMP%NOTFOUND;
    END LOOP;

    CLOSE TEMP;
END;
/

SELECT * FROM banknew;